---
- name: test work
  hosts: all
  tasks:
    - name: install python3
      become: true
      yum:
        name:
          - python3
          - python3-devel
          - python3-pip
          - python3-setuptools
        state: present
      when: ansible_facts['distribution'] == "CentOS"

    - name: install git
      become: true
      package:
        name: git
        state: latest

    - name: checkout code from github
      git:
        repo: "https://github.com/xiaopeng163/flask-ansible-demo"
        dest: /root/flask-ansible-demo

    - name: pip install requirements
      pip:
        requirements: /root/flask-ansible-demo/requirements.txt
        state: present
        virtualenv: /root/flask-ansible-demo/.env
        virtualenv_command: /usr/bin/python3 -m venv

    - name: start flask app
      shell: nohup /root/flask-ansible-demo/.env/bin/python /root/flask-ansible-demo/wsgi.py&
      register: flaskoutput

    - name: print stdout
      debug:
        var: flaskoutput
