- name: install python3
  become: true
  yum:
    name:
      - python3
      - python3-devel
      - python3-pip
      - python3-setuptools
    state: present
  when: ansible_facts['distribution'] == "CentOS"
